# Generated by Django 3.2 on 2021-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='problem',
        ),
        migrations.AddField(
            model_name='task',
            name='problem',
            field=models.ManyToManyField(to='math_test.Problem'),
        ),
    ]
